### ISSUE TITLE
What's going on with the bullets?

### ISSUE THREAD

**Issue by congdon** [OpenMaine/openmaine-website#18]
It looks fine on my desktop, but on the web, the bullets moved all the way to the left.

a. I had a fresh pull from GitHub and only added the COVID19 section when this started... I think?
b. w3.org tells me that this is valid HTML, FWIW.

Not hugely urgent, just something to fix.

**Comment by inomyabcs** [comment]
Hmm,,, Strange that you have to add a style to this now. However, the following attribute will align the bullets with the text: `style="list-style-position: inside"`. Include it with the ul tags and it should resolve.

**Comment by congdon** [comment]
Thank you, Chris! I think @AmyMcGann knows how to fix it using BootStrap syntax, and since everything is Bootstrap-y, maybe better to remain in that paradigm? (Though I am all for overriding it in a pinch.) Sounds like Amy will have some time later today, so I will leave it for now.

Thanks again!

**Comment by congdon** [comment]
(Fixed by Amy... a few weeks ago. Thank you, Amy!)
