### ISSUE TITLE
openmaine.org does not redirect port 80 to port 443

### ISSUE THREAD

**Issue by dfithian** [OpenMaine/openmaine-website#25]
I noticed that openmaine.org has an SSL certificate but that `http://openmaine.org` does not redirect to `https://openmaine.org`.

@congdon How is the website served? Is it apache/nginx? Can we add a rule to redirect port 80 to port 443?

**Comment by congdon** [comment]
Hi Dan... Good catch, thank you! I do not have your level of sophistication with these things, and will be happy to adjust based on your recommendations and help. We are hosted on InMotion, on a shared server, FWIW.

I am a little crunched for time right now, but will have a look when I get a chance.

**Comment by dfithian** [comment]
Clare did this!

**Comment by congdon** [comment]
Many thanks to Dan for pointing out the issue and helping me figure out how best to fix it with our hosting.
